=== Hunter99011/OVWBWLWebXML/beadando/XMLSchemaOVWBWL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Típusok -->
    <xs:simpleType name="TelefonSzamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+?\d{1,3}( \d{1,4}){2,3}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="KolcsonozhetoTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen" />
            <xs:enumeration value="nem" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="KonyvtariRendszer">
        <xs:complexType>
            <xs:sequence>

                <!-- Könyvek -->
                <xs:element name="Konyvek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Konyv" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="KonyvID" type="xs:integer" />
                                        <xs:element name="Cim" type="xs:string" />
                                        <xs:element name="Szerzo" type="xs:string" />
                                        <xs:element name="KiadasEve" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Példányok -->
                <xs:element name="Peldanyok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Peldany" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="LeltariSzam" type="xs:string" />
                                        <xs:element name="KonyvID" type="xs:integer" />
                                        <xs:element name="Allapot" type="xs:string" />
                                        <xs:element name="Polcszam" type="xs:string" />
                                        <xs:element name="Kolcsonozheto" type="KolcsonozhetoTipus" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Kiadók -->
                <xs:element name="Kiadok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Kiado" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="KiadoID" type="xs:integer" />
                                        <xs:element name="Nev" type="xs:string" />
                                        <xs:element name="Szekhely" type="xs:string" />
                                        <xs:element name="Telefonszam" type="TelefonSzamTipus" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Olvasók -->
                <xs:element name="Olvasok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Olvaso" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="OlvasoID" type="xs:integer" />
                                        <xs:element name="Nev">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Vezeteknev" type="xs:string" />
                                                    <xs:element name="Keresztnev" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Lakcim" type="xs:string" />
                                        <xs:element name="Telefonszam" type="TelefonSzamTipus" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Tagdíjak -->
                <xs:element name="Tagdijak">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Tagdij" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="TagdijID" type="xs:integer" />
                                        <xs:element name="Osszeg" type="xs:integer" />
                                        <xs:element name="Kedvezmeny" type="xs:integer" />
                                    </xs:sequence>
                                    <xs:attribute name="ev" type="xs:gYear" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                 <!-- Kiadasok -->
                <xs:element name="Kiadasok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Kiadja" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="KonyvID" type="xs:integer" />
                                        <xs:element name="KiadoID" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Kolcsonzesek -->
                <xs:element name="Kolcsonzesek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Kolcsonzi" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="KolcsonzesID" type="xs:string" />
                                        <xs:element name="OlvasoID" type="xs:integer" />
                                        <xs:element name="LeltariSzam" type="xs:string" />
                                        <xs:element name="Datum" type="xs:date" />
                                        <xs:element name="Visszahozva" type="xs:date" />
                                        <xs:element name="Buntetes" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Fizetesek -->
                <xs:element name="Fizetesek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Fizetes" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="TagdijID" type="xs:integer" />
                                        <xs:element name="OlvasoID" type="xs:integer" />
                                        <xs:element name="Datum" type="xs:date" />
                                        <xs:element name="Kedvezmenyes">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Igen" />
                                                    <xs:enumeration value="Nem" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="FizetesiMod">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Készpénz" />
                                                    <xs:enumeration value="Bankkártya" />
                                                    <xs:enumeration value="Átutalás" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>

        <!-- Egyedi kulcsok és referenciák -->
        <xs:unique name="UniqueKonyvID">
            <xs:selector xpath="Konyvek/Konyv" />
            <xs:field xpath="KonyvID" />
        </xs:unique>
        <xs:unique name="UniqueKiadoID">
            <xs:selector xpath="Kiadok/Kiado" />
            <xs:field xpath="KiadoID" />
        </xs:unique>
        <xs:keyref name="KonyvPeldanyReferencias" refer="UniqueKonyvID">
            <xs:selector xpath="Peldanyok/Peldany" />
            <xs:field xpath="KonyvID" />
        </xs:keyref>
    </xs:element>
</xs:schema>

=== Hunter99011/OVWBWLWebXML/beadando/DOMParseOVWBWL/XMLNeptunkod1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<KonyvtariRendszer xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaOVWBWL.xsd">
      
  <!-- Könyvek példányai -->
      
  <Konyvek>
            
    <Konyv>
                  
      <KonyvID>1</KonyvID>
                  
      <Cim>A világ története</Cim>
                  
      <Szerzo>Erkel Mária</Szerzo>
                  
      <KiadasEve>1989</KiadasEve>
              
    </Konyv>
            
    <Konyv>
                  
      <KonyvID>2</KonyvID>
                  
      <Cim>Űrutazás alapjai</Cim>
                  
      <Szerzo>Alma Aladár</Szerzo>
                  
      <KiadasEve>2001</KiadasEve>
              
    </Konyv>
            
    <Konyv>
                  
      <KonyvID>3</KonyvID>
                  
      <Cim>Matematika alapjai</Cim>
                  
      <Szerzo>Gyári Ferenc</Szerzo>
                  
      <KiadasEve>1977</KiadasEve>
              
    </Konyv>
        
  </Konyvek>
      
  <!-- Az egyes könyvek egyes példányai -->
      
  <Peldanyok>
            
    <Peldany>
                  
      <LeltariSzam>001</LeltariSzam>
                  
      <KonyvID>1</KonyvID>
                  
      <Allapot>Jó</Allapot>
                  
      <Polcszam>101A</Polcszam>
                  
      <Kolcsonozheto>Igen</Kolcsonozheto>
              
    </Peldany>
            
    <Peldany>
                  
      <LeltariSzam>002</LeltariSzam>
                  
      <KonyvID>2</KonyvID>
                  
      <Allapot>Közepes</Allapot>
                  
      <Polcszam>202B</Polcszam>
                  
      <Kolcsonozheto>Nem</Kolcsonozheto>
              
    </Peldany>
            
    <Peldany>
                  
      <LeltariSzam>003</LeltariSzam>
                  
      <KonyvID>2</KonyvID>
                  
      <Allapot>Jó</Allapot>
                  
      <Polcszam>202C</Polcszam>
                  
      <Kolcsonozheto>Igen</Kolcsonozheto>
              
    </Peldany>
            
    <Peldany>
                  
      <LeltariSzam>004</LeltariSzam>
                  
      <KonyvID>3</KonyvID>
                  
      <Allapot>Kiváló</Allapot>
                  
      <Polcszam>303C</Polcszam>
                  
      <Kolcsonozheto>Igen</Kolcsonozheto>
              
    </Peldany>
        
  </Peldanyok>
      
  <!-- A könyvkiadók példányai -->
      
  <Kiadok>
            
    <Kiado>
                  
      <KiadoID>1001</KiadoID>
                  
      <Nev>Mentor Kiadó</Nev>
                  
      <Szekhely>Budapest</Szekhely>
                  
      <Telefonszam>+36 1 234 5678</Telefonszam>
              
    </Kiado>
            
    <Kiado>
                  
      <KiadoID>1002</KiadoID>
                  
      <Nev>Űrtudományi Kiadó</Nev>
                  
      <Szekhely>Debrecen</Szekhely>
                  
      <Telefonszam>+36 52 345 6789</Telefonszam>
              
    </Kiado>
            
    <Kiado>
                  
      <KiadoID>1003</KiadoID>
                  
      <Nev>Amicus Kiadó</Nev>
                  
      <Szekhely>Pécs</Szekhely>
                  
      <Telefonszam>+36 72 456 7890</Telefonszam>
              
    </Kiado>
        
  </Kiadok>
      
  <!-- Olvasók példányai -->
      
  <Olvasok>
            
    <Olvaso>
                  
      <OlvasoID>101</OlvasoID>
                  
      <Nev>
                        
        <Vezeteknev>Kovács</Vezeteknev>
                        
        <Keresztnev>Péter</Keresztnev>
                    
      </Nev>
                  
      <Lakcim>Budapest, Fő utca 1.</Lakcim>
                  
      <Telefonszam>+36 30 123 4567</Telefonszam>
              
    </Olvaso>
            
    <Olvaso>
                  
      <OlvasoID>102</OlvasoID>
                  
      <Nev>
                        
        <Vezeteknev>Nagy</Vezeteknev>
                        
        <Keresztnev>Anna</Keresztnev>
                    
      </Nev>
                  
      <Lakcim>Debrecen, Kossuth utca 2.</Lakcim>
                  
      <Telefonszam>+36 30 234 5678</Telefonszam>
              
    </Olvaso>
            
    <Olvaso>
                  
      <OlvasoID>103</OlvasoID>
                  
      <Nev>
                        
        <Vezeteknev>Tóth</Vezeteknev>
                        
        <Keresztnev>János</Keresztnev>
                    
      </Nev>
                  
      <Lakcim>Pécs, Rákóczi út 3.</Lakcim>
                  
      <Telefonszam>+36 30 345 6789</Telefonszam>
              
    </Olvaso>
        
  </Olvasok>
      
  <!-- A tagdíjak -->
      
  <Tagdijak>
            
    <Tagdij ev="2023">
                  
      <TagdijID>100</TagdijID>
                  
      <Osszeg>1000</Osszeg>
                  
      <Kedvezmeny>200</Kedvezmeny>
              
    </Tagdij>
        
  </Tagdijak>
      
  <!-- Kiadja kapcsolat -->
      
  <Kiadasok>
            
    <Kiadja>
                  
      <KonyvID>1</KonyvID>
                  
      <KiadoID>1001</KiadoID>
              
    </Kiadja>
            
    <Kiadja>
                  
      <KonyvID>2</KonyvID>
                  
      <KiadoID>1002</KiadoID>
              
    </Kiadja>
            
    <Kiadja>
                  
      <KonyvID>3</KonyvID>
                  
      <KiadoID>1003</KiadoID>
              
    </Kiadja>
        
  </Kiadasok>
      
  <!-- Kölcsönzi kapcsolat -->
      
  <Kolcsonzesek>
            
    <Kolcsonzi>
                  
      <KolcsonzesID>001</KolcsonzesID>
                  
      <OlvasoID>101</OlvasoID>
                  
      <LeltariSzam>001</LeltariSzam>
                  
      <Datum>2024-01-01</Datum>
                  
      <Visszahozva>2024-01-10</Visszahozva>
                  
      <Buntetes>0</Buntetes>
              
    </Kolcsonzi>
            
    <Kolcsonzi>
                  
      <KolcsonzesID>002</KolcsonzesID>
                  
      <OlvasoID>102</OlvasoID>
                  
      <LeltariSzam>002</LeltariSzam>
                  
      <Datum>2024-01-05</Datum>
                  
      <Visszahozva>2024-01-15</Visszahozva>
                  
      <Buntetes>500</Buntetes>
              
    </Kolcsonzi>
            
    <Kolcsonzi>
                  
      <KolcsonzesID>003</KolcsonzesID>
                  
      <OlvasoID>103</OlvasoID>
                  
      <LeltariSzam>003</LeltariSzam>
                  
      <Datum>2024-01-10</Datum>
                  
      <Visszahozva>2024-01-20</Visszahozva>
                  
      <Buntetes>0</Buntetes>
              
    </Kolcsonzi>
        
  </Kolcsonzesek>
      
  <!-- Fizetések kapcsolata -->
      
  <Fizetesek>
            
    <Fizetes>
                  
      <TagdijID>100</TagdijID>
                  
      <OlvasoID>101</OlvasoID>
                  
      <Datum>2024-01-01</Datum>
                  
      <Kedvezmenyes>Igen</Kedvezmenyes>
                  
      <FizetesiMod>Készpénz</FizetesiMod>
              
    </Fizetes>
            
    <Fizetes>
                  
      <TagdijID>100</TagdijID>
                  
      <OlvasoID>102</OlvasoID>
                  
      <Datum>2024-08-05</Datum>
                  
      <Kedvezmenyes>Nem</Kedvezmenyes>
                  
      <FizetesiMod>Bankkártya</FizetesiMod>
              
    </Fizetes>
            
    <Fizetes>
                  
      <TagdijID>100</TagdijID>
                  
      <OlvasoID>103</OlvasoID>
                  
      <Datum>2024-01-10</Datum>
                  
      <Kedvezmenyes>Igen</Kedvezmenyes>
                  
      <FizetesiMod>Átutalás</FizetesiMod>
              
    </Fizetes>
        
  </Fizetesek>
  
</KonyvtariRendszer>
